spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://dpg-d05s7fa4d50c73apdvbg-a.oregon-postgres.render.com:5432/projectdb_f9wz?sslmode=require
    username: projectdb_f9wz_user
    password: nVCshY69EfC7Uo7TyMqdbmA8DBHKPJJk
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
  servlet:
    context-path: /
